[package]
name = "flowchain-runtime"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
safe-mix = { version = "1.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
version = { package = "sr-version", git = "https://github.com/paritytech/substrate.git", default-features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate.git", default-features = false }
substrate-session = { git = "https://github.com/paritytech/substrate.git", default-features = false }
aura-primitives = { package = "substrate-consensus-aura-primitives", git = "https://github.com/paritytech/substrate.git", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate.git", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/paritytech/substrate.git", default-features = false }
tx-pool-api = { package = "substrate-transaction-pool-runtime-api", git = "https://github.com/paritytech/substrate.git", default-features = false }
block-builder-api = { package = "substrate-block-builder-runtime-api", git = "https://github.com/paritytech/substrate.git", default-features = false }
sr-api = { git = "https://github.com/paritytech/substrate.git", default-features = false }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate.git", default-features = false }

system = { package = "frame-system", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate.git", default-features = false }

orml-oracle = { path = "../orml/oracle", default-features = false }
orml-tokens = { path = "../orml/tokens", default-features = false }
orml-currencies = { path = "../orml/currencies", default-features = false }
orml-prices = { path = "../orml/prices", default-features = false }
orml-traits = { path = "../orml/traits", default-features = false }
orml-utilities = { path = "../orml/utilities", default-features = false }

synthetic-tokens = { package = "module-synthetic-tokens", path = "../modules/synthetic-tokens", default-features = false }
synthetic-protocol = { package = "module-synthetic-protocol", path = "../modules/synthetic-protocol", default-features = false }
traits = { package = "module-traits", path = "../modules/traits", default-features = false }
module-primitives = { path = "../modules/primitives", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"rstd/std",
	"runtime-io/std",
	"primitives/std",
	"sr-primitives/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"substrate-session/std",
	"tx-pool-api/std",
	"sr-api/std",
	"block-builder-api/std",
	"inherents/std",
	"aura-primitives/std",
	"system/std",
	"frame-support/std",
	"frame-executive/std",
	"pallet-balances/std",
	"pallet-aura/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"orml-oracle/std",
	"orml-tokens/std",
	"orml-currencies/std",
	"orml-prices/std",
	"orml-traits/std",
	"orml-utilities/std",
	"module-primitives/std",
	"synthetic-tokens/std",
	"synthetic-protocol/std",
	"traits/std",
]
