[package]
name = "flowchain-runtime"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
safe-mix = { version = "1.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sp-std", git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime-io = { package = "sp-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
version = { package = "sp-version", git = "https://github.com/paritytech/substrate.git", default-features = false }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate.git", default-features = false }
aura-primitives = { package = "sp-consensus-aura", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false }
offchain-primitives = { package = "sp-offchain", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-transaction-pool = { package = "sp-transaction-pool", git = "https://github.com/paritytech/substrate.git", default-features = false }
block-builder-api = { package = "sp-block-builder", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", default-features = false }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate.git", default-features = false }

system = { package = "frame-system", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate.git", default-features = false }

orml-oracle = { path = "../orml/oracle", default-features = false }
orml-tokens = { path = "../orml/tokens", default-features = false }
orml-currencies = { path = "../orml/currencies", default-features = false }
orml-prices = { path = "../orml/prices", default-features = false }
orml-traits = { path = "../orml/traits", default-features = false }
orml-utilities = { path = "../orml/utilities", default-features = false }

synthetic-tokens = { package = "module-synthetic-tokens", path = "../modules/synthetic-tokens", default-features = false }
synthetic-protocol = { package = "module-synthetic-protocol", path = "../modules/synthetic-protocol", default-features = false }
traits = { package = "module-traits", path = "../modules/traits", default-features = false }
module-primitives = { path = "../modules/primitives", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"rstd/std",
	"runtime-io/std",
	"primitives/std",
	"sp-runtime/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"sp-session/std",
	"sp-transaction-pool/std",
	"sp-api/std",
	"block-builder-api/std",
	"inherents/std",
	"aura-primitives/std",
	"system/std",
	"frame-support/std",
	"frame-executive/std",
	"pallet-balances/std",
	"pallet-aura/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"orml-oracle/std",
	"orml-tokens/std",
	"orml-currencies/std",
	"orml-prices/std",
	"orml-traits/std",
	"orml-utilities/std",
	"module-primitives/std",
	"synthetic-tokens/std",
	"synthetic-protocol/std",
	"traits/std",
]
