[package]
name = "module-margin-protocol"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime_io = { package = "sp-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sp-std", git = "https://github.com/paritytech/substrate.git", default-features = false }

frame-support = { package = "frame-support", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate.git", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"runtime_io/std",
	"rstd/std",
	"frame-support/std",
	"frame-system/std",
]
